### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by feinstaub** [loh-tar/KatePlugin-IndexView#4]
Coming from https://github.com/loh-tar/KatePlugin-IndexView/issues/1, maybe one solution could be not display any icons. Here is an example how this could look like:

![image](https://user-images.githubusercontent.com/368412/53680757-2275d800-3ce0-11e9-95c2-50766594b39e.png)

Too many different icons can lead to a rather restless picture :-)

![image](https://user-images.githubusercontent.com/368412/53680782-5650fd80-3ce0-11e9-913c-01727c4b33c2.png)

**Comment by loh-tar** [comment]
Good examples to argue, well done. But I will not remove these icons completely. I like them someway. I would accept a patch to make them optional. 

Not sure which would be best, global on the config page or individual by context menu. Perhaps may someone like to see icons in one file type but not in the other.

Should I have the mood and time I may do it, but it's for me not important.
